### ISSUE TITLE
US07 - Fazer Cadastro

### ISSUE THREAD

**Issue by LGomees** [fga-eps-mds/2021.1-PCTs-Frontend#18]
# Nome da Issue

US[07] - Criação do frontend para o Cadastro.

## Descrição

Eu, como usuário, desejo fazer o meu cadastro no site.

## Tarefas

- [ ] Criar página para cadastro
- [ ] Criar rota para a página
- [ ] Criar botão de referência para a página de cadastro dentro do formulário de login
- [ ] Fazer a conexão com a API de Usuários

## Critérios de aceitação

- [ ] Deve mostrar o formulário de cadastro
- [ ] Fazer verificação via email
- [ ] Comunicação com a API de Usuários

**Comment by Ridersk** [comment]
Funcionalidade cancelada
