### ISSUE TITLE
US08 - Editar Cadastro

### ISSUE THREAD

**Issue by LGomees** [fga-eps-mds/2021.1-PCTs-Frontend#19]
# Nome da Issue

US[07] - Fazer frontend para edição de cadastro

## Descrição

Eu, como usuário, desejo editar o meu cadastro.

## Tarefas

- [ ] Criar página para mostrar as informações do cadastro
- [ ] Criar rota para a página
- [ ] Fazer a conexão com a API de Usuários

## Critérios de aceitação

- [ ] Mostrar informações atuais
- [ ] Confirmar edição dos dados através da senha do usuário
- [ ] Comunicação com a API de Usuários

## Dependência

Issues necessárias para a continuidade ou conclusão desta Issue

- [x] #18

**Comment by Ridersk** [comment]
Funcionalidade cancelada
